import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fixture = JSON.parse(await readFile(process.env.EXECUTION_FIXTURE, 'utf8'));
const base = process.env.EXECUTION_BASE;
const url = `/api/workspaces/${fixture.workspace_id}/tasks/${fixture.task_id}/file-edit-proposals/${fixture.proposal_id}/apply`;
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_EXECUTABLE });
try {
    const page = await browser.newPage({ viewport: { width: 1366, height: 900 }, colorScheme: 'light' });
    const errors = [], responses = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('response', response => { if (response.url().endsWith('/apply')) responses.push(response.status()); });
    await page.goto(base);
    await page.getByRole('checkbox').waitFor();
    assert.ok(await page.getByRole('button', { name: '应用样例提案', exact: true }).isDisabled());
    const rejected = await page.request.post(base + url, { headers: { Origin: base }, data: { action: 'apply', path: '/not-allowed' } });
    assert.equal(rejected.status(), 422);
    const pending = page.waitForResponse(response => response.url() === base + url);
    await page.getByRole('checkbox').check();
    await page.getByRole('button', { name: '应用样例提案', exact: true }).click();
    const response = await pending;
    assert.equal(response.status(), 200);
    const receipt = await response.json();
    assert.equal(receipt.file_status, 'replaced');
    assert.equal(receipt.application_status, 'applied');
    assert.equal(receipt.cleanup_complete, true);
    assert.equal(response.headers()['cache-control'], 'no-store');
    assert.equal(response.headers()['set-cookie'], undefined);
    assert.deepEqual(Object.keys(receipt).sort(), ['application_status', 'cleanup_complete', 'code', 'file_status', 'proposal_id', 'task_id', 'workspace_id']);
    await page.getByText('已确认登记应用成功', { exact: true }).waitFor();
    assert.ok(await page.getByRole('button', { name: '应用样例提案', exact: true }).isDisabled());
    await page.reload();
    await page.getByText('已确认登记应用成功', { exact: true }).waitFor();
    assert.deepEqual(responses, [200]);
    // 绕过UI直接重复HTTP，后端仍不得再次替换文件。
    const before = await readFile(fixture.root + '/example.txt');
    const { stat } = await import('node:fs/promises');
    const beforeStat = await stat(fixture.root + '/example.txt');
    const repeated = await page.request.post(base + url, { headers: { Origin: base }, data: { action: 'apply' } });
    const afterStat = await stat(fixture.root + '/example.txt');
    assert.equal((await readFile(fixture.root + '/example.txt')).equals(before), true);
    assert.equal(afterStat.ino, beforeStat.ino);
    assert.equal(afterStat.mtimeMs, beforeStat.mtimeMs);
    const repeatedBody = await repeated.json();
    assert.notEqual(repeatedBody.code, 'proposal_application_applied');
    assert.deepEqual(errors, []);
    await page.screenshot({ path: process.env.EXECUTION_OUTPUT + '/real-success.png', fullPage: true });
    await writeFile(process.env.EXECUTION_OUTPUT + '/browser.json', JSON.stringify({ receipt, repeatStatus: repeated.status(), repeatCode: repeatedBody.code, repeatFileUnchanged: true, pageErrors: errors, uiRequests: responses.length }, null, 4));
} finally { await browser.close(); }
