import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const { chromium } = createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE || 'playwright');
const output = fileURLToPath(new URL('../../output/playwright/project-write-grant-integration/', import.meta.url));
const item = JSON.parse(await readFile(output + 'fixtures.json', 'utf8'))[0];
const base = process.env.AUTH_TEST_BASE_URL;
const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_EXECUTABLE });
const page = await browser.newPage({ viewport: { width: 1366, height: 900 } });
page.setDefaultTimeout(30000);
const errors = [];
let applies = 0;
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/write-grant/apply')) applies++; });
try {
    await page.goto(`${base}/?workspace=${item.workspace_id}&task=${item.task_id}`);
    await page.getByRole('button', { name: '查看改动', exact: true }).click();
    const pane = page.getByRole('complementary', { name: '文件改动', exact: true });
    await pane.locator('summary').filter({ hasText: 'example.txt' }).click();
    await pane.getByRole('button', { name: '查看提案详情', exact: true }).press('Enter');
    await pane.getByRole('button', { name: '批准提案', exact: true }).click();
    await pane.getByText('已确认批准此提案。应用状态以执行结果为准。', { exact: true }).waitFor();
    await pane.locator('summary').filter({ hasText: '普通项目写入许可' }).click();
    await pane.getByRole('button', { name: '查询许可状态' }).click();
    await pane.getByRole('button', { name: '发放本提案许可', exact: true }).click();
    await pane.getByRole('button', { name: '确认发放许可' }).click();
    await pane.getByRole('button', { name: '应用已批准的项目修改' }).press('Enter');
    await pane.getByText('文件修改已应用。', { exact: true }).waitFor();
    assert.equal(applies, 1);
    await pane.locator('summary').filter({ hasText: '应用审计与恢复' }).click();
    await pane.getByRole('button', { name: '查询审计记录' }).click();
    await pane.getByRole('button', { name: '生成恢复提案', exact: true }).click();
    await pane.getByText('恢复提案已生成。刷新改动列表，审阅并批准后再应用。', { exact: true }).waitFor();
    await pane.getByRole('button', { name: '刷新改动', exact: true }).click();
    const reverse = pane.locator('details.group').first();
    await reverse.locator('summary').first().click();
    await reverse.getByRole('button', { name: '查看提案详情', exact: true }).click();
    await reverse.getByRole('button', { name: '批准提案', exact: true }).click();
    await reverse.getByText('已确认批准此提案。应用状态以执行结果为准。', { exact: true }).waitFor();
    await reverse.locator('summary').filter({ hasText: '普通项目写入许可' }).click();
    await reverse.getByRole('button', { name: '查询许可状态' }).click();
    await reverse.getByRole('button', { name: '发放本提案许可', exact: true }).click();
    await reverse.getByRole('button', { name: '确认发放许可' }).click();
    await reverse.getByRole('button', { name: '应用已批准的项目修改' }).click();
    await reverse.getByText('文件修改已应用。', { exact: true }).waitFor();
    assert.equal(applies, 2);
    await page.screenshot({ path: output + 'apply-1366.png', fullPage: true });
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.screenshot({ path: output + 'apply-1920.png', fullPage: true });
    assert.deepEqual(errors, []);
    await writeFile(output + 'apply-browser.json', JSON.stringify({ applies, errors, widths: [1366,1920] }));
} finally { await browser.close(); }
